spring:
    datasource:
      name: test
      url: jdbc:mysql://112.74.111.197:3306/myblog?characterEncoding=utf-8&useSSL=false
      username: leige
      password: fang201314
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    freemarker:
      allow-request-override: false
      cache: true
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      suffix: .ftl
      template-loader-path: classpath:/templates
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    profiles:
      active: dev
jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: "Bearer "
    route:
      authentication:
        path: auth
        refresh: refresh
        register: "auth/register"